Feature/user auth
Bookquest-projects/backend pull request #17
Opened 2024-08-29 12:05 UTC by SlWa99

2024-08-30 08:03 UTC, emilie-h requested changes

2024-08-30 09:42 UTC, SlWa99 commented on db/db_create.sql
> +    `name` VARCHAR(45) NOT NULL,
@Kalysso Can you explain this choice ?

2024-08-30 09:43 UTC, SlWa99 commented on db/db_create.sql
> +    `name` VARCHAR(45) NOT NULL,
@Kalysso Same here

2024-08-30 09:43 UTC, SlWa99 commented on db/db_create.sql
> +    `favorite` TINYINT UNSIGNED DEFAULT NULL,
@Kalysso Same here

2024-08-30 10:34 UTC, Kalysso commented on db/db_create.sql
> +    `favorite` TINYINT UNSIGNED DEFAULT NULL,
BOOL is TINYINT(1) for MySQL. I'll change for better reading

2024-08-30 11:03 UTC, emilie-h approved these changes

2024-08-30 11:04 UTC, emilie-h submitted a review, later dismissed

2024-08-31 16:39 UTC, emilie-h submitted a review, later dismissed

2024-09-01 12:50 UTC, BetterBlood approved these changes

2024-09-01 13:00 UTC, merged